import os
from dotenv import load_dotenv

load_dotenv()

TELEGRAM_API_ID = os.getenv("TELEGRAM_API_ID", "REDACTED")
TELEGRAM_API_HASH = os.getenv("TELEGRAM_API_HASH", "REDACTED")
TELEGRAM_PHONE = os.getenv("TELEGRAM_PHONE", "REDACTED")
CHANNEL_NAME = "REDACTED"
DB_URL = "REDACTED"

SESSION_NAME = "REDACTED"
DEFAULT_EXPIRATION_MINUTES = "REDACTED"
MATCH_TOLERANCE_SECONDS = "REDACTED"
DEFAULT_PAYOUT_RATE = "REDACTED"

RAW_MESSAGES_PATH = "REDACTED"
REPORTS_DIR = "REDACTED"
EXPORTS_DIR = "REDACTED"
LOGS_DIR = "REDACTED"
